
apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-restapp
  labels: 
    app: backend-restapp
    tier: backend
    
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: backend-restapp
  template:
    metadata:
      labels:
        app: backend-restapp
        tier: backend
    spec:
      containers:
        - name: backend-restapp
          image: douglasdb/my-vertx-native-service:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: backend-service ## VERY IMPORTANT ## NGIX PROXYPASS E.G
  labels:
    app: backend-restapp
    tier: backend
    
spec:
  type: ClusterIP # default if no specified
  selector:
    app: backend-restapp
  ports:
    - name: http
      port: 8080 # ClustserIP Service Port
      targetPort: 8080
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ngnix-app
  labels:
    app: frontend-nginx-app
    tier: frontend

spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-ngnix-app
  template:
    metadata:
      labels:
        app: frontend-nginx-app
        tier: frontend
    spec:
      containers:
      - name: my-reactjs-front
        image: douglasdb/nginx-reactjs-app:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-nginx-app-service
  labels:
    app: frontend-nginx-app
    tier: frontend
spec:
  type: NodePort
  selector:
    app: frontend-nginx-app
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 31234
